@startuml
|사용자|
start

:캐릭터 목록 조회;
:원하는 캐릭터 선택;
:채팅방 생성;

:통화 시작;

|클라이언트|
fork
    :캐릭터 모델 로드;
fork again
    :웹소켓 구독;
end fork

repeat
|사용자|
:녹음 버튼 클릭;

|클라이언트|
:음성 메시지 전송;

|서버|
:캐릭터 응답 생성;
:캐릭터 음성 변환;
:캐릭터 음성 웹소켓에 발행;

|클라이언트|
:캐릭터 음성 재생;
:캐릭터 립싱크 처리;

repeat while (통화 종료할 때까지)

|사용자|
:통화 종료;
stop
@enduml