steps:
  - name: 'gradle:8.13-jdk21'
    entrypoint: 'gradle'
    args: ['clean', 'build']

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'instances', 'update-container', 'instance-20250319-105832',
           '--zone', 'asia-northeast1',
           '--container-image', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

timeout: 1200s
