services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: charactalk-application
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    restart: always
    image: ${DOCKER_IMAGE}:latest
    volumes:
      - ./gcp-key.json:/gcp-key.json:ro