spring:
  config:
    import:
      - api-config.yml
      - app-config.yml
      - persistence-config.yml
      - security-config.yml
      - optional:file:.env[.properties]

gcp:
  speech:
    enabled: false
    recognizer: projects/977431648702/locations/global/recognizers/charactalk-speech-to-text

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    knu.ridi.charactalk: DEBUG
    org.springframework.web.socket: DEBUG
    com.google.cloud.speech.v2: DEBUG

---
spring:
  config:
    activate:
      on-profile: main

logging:
  level:
    knu.ridi.charactalk: WARN
    org.springframework.web.socket: WARN