server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: None

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            redirect-uri: "{baseUrl}/login/oauth2/code/google"
#            scope:
#              - profile
#              - email

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    charactalk: DEBUG

---
spring:
  config:
    activate:
      on-profile: main

logging:
  level:
    charactalk: DEBUG
