ALTER TABLE MEMBER DROP COLUMN nickname;
ALTER TABLE MEMBER ADD COLUMN name VARCHAR(255) NULL;
ALTER TABLE MEMBER ADD COLUMN picture VARCHAR(255) NULL;
ALTER TABLE MEMBER ADD COLUMN role VARCHAR(255) NULL;